---
- name: Configure static local ipv6 address (ULA-based)
  become: yes
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/90-local_ipv6
    group: root
    mode: "0644"
    owner: root
    src: local_ipv6.j2
  notify: Restart networking
...
