---
- name: Stop second interface
  listen: Restart networking to start br1
  become: yes
  ansible.builtin.systemd:
    name: ifup@{{ second_interface }}
    enabled: false
    state: stopped
- name: Reboot to ensure network correctly refreshed
  listen: Restart networking to start br1
  become: yes
  ansible.builtin.reboot:
    search_paths:
    - /usr/sbin
    - /lib/molly-guard
...
