---
- name: Stop second interface
  listen: Restart networking to start br1
  become: yes
  ansible.builtin.systemd:
    name: ifup@{{ second_interface }}
    enabled: false
    state: stopped
- name: Restart networking to enable br1
  listen: Restart networking to start br1
  become: yes
  ansible.builtin.systemd:
    name: networking
    state: restarted
...
