---
- name: Add a hostname alias for gdav use
  become: yes
  ansible.builtin.template:
    dest: /etc/hosts
    group: root
    mode: "0644"
    owner: root
    src: hosts.j2
- name: Persist hostname alias for gdav use
  become: yes
  ansible.builtin.template:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    group: root
    mode: "0644"
    owner: root
    src: hosts.debian.tmpl.j2
- name: Ensure private CA certificate (for verifying internal hosts) is present
  ansible.builtin.import_tasks: task-cert_private_ca.yml
  notify: Restart dovecot
- name: Ensure private server certificate and key (for incoming internal hosts)
  ansible.builtin.import_tasks: task-cert_private_server.yml
  notify: Restart dovecot
- name: Ensure private client certificate and key (for submission relay)
  ansible.builtin.import_tasks: task-cert_private_client.yml
  notify: Restart dovecot
- name: Configure dovecot as mailbox server
  become: yes
  block:
  - name: Set base mail directory permissions to allow autocreation of homes
    ansible.builtin.file:
      group: root
      mode: "1777"
      owner: root
      path: /var/vmail
  - name: Ensure dovecot packages present
    ansible.builtin.apt:
      name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-managesieved
      - dovecot-sieve
      - dovecot-submissiond
  - name: Create dovecot authentication config
    ansible.builtin.copy:
      dest: /etc/dovecot/conf.d/10-auth.conf
      group: root
      mode: "0644"
      owner: root
      src: dovecot-conf.d/10-auth.conf
    notify: Restart dovecot
  - name: Create dovecot password file config
    ansible.builtin.copy:
      dest: /etc/dovecot/conf.d/auth-passwdfile.conf.ext
      group: root
      mode: "0644"
      owner: root
      src: dovecot-conf.d/auth-passwdfile.conf.ext
    notify: Restart dovecot
  - name: Configure dovecot listeners
    ansible.builtin.template:
      dest: /etc/dovecot/conf.d/10-master.conf
      group: root
      mode: "0644"
      owner: root
      src: dovecot-conf.d/10-master.conf.j2
    notify: Restart dovecot
  - name: Configure dovecot local overrides to config
    ansible.builtin.template:
      dest: /etc/dovecot/local.conf
      group: root
      mode: "0644"
      owner: root
      src: dovecot-local.conf.j2
    notify: Restart dovecot
  - name: Configure dovecot users
    ansible.builtin.template:
      dest: /etc/dovecot/users
      group: dovecot
      mode: "0640"
      owner: mail
      src: users.j2
    notify: Restart dovecot
- name: Configure Fail2Ban for Dovecot with Sieve
  become: yes
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/dovecot.local
    group: root
    mode: "0644"
    owner: root
    src: dovecot_jail.local
  notify: Restart Fail2Ban
- name: Allow access to Dovecot through firewall
  become: yes
  block:
  - name: Allow health check from OVH RTM
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: "{{ item }}"
      to_port: "{{ health_check_port_dovecot }}"
    loop: "{{ remote_monitoring_ips }}"
  - name: Allow IMAP from anywhere
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: any
      to_port: "{{ imap_port }}"
  - name: Allow ManageSieve from anywhere
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: any
      to_port: "{{ sieve_port }}"
  - name: Allow Submission from anywhere
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: any
      to_port: "{{ submission_port }}"
  - name: Allow LMTP from local (internal) network (v4)
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: "{{ v4nat_net }}/{{ v4nat_prefix }}"
      to_port: "{{ lmtp_port }}"
  - name: Allow LMTP from local (internal) network (v6)
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      src: "{{ v6nat_net }}/{{ v6nat_prefix }}"
      to_port: "{{ lmtp_port }}"
...
