---
- name: Rehash sender transport map
  become: yes
  ansible.builtin.command: postmap hash:/etc/postfix/sender_default_transport_map
- name: Rehash virtual mailboxes
  become: yes
  ansible.builtin.command: postmap hash:/etc/postfix/vmailbox
- name: Rehash virtual aliases
  become: yes
  ansible.builtin.command: postmap hash:/etc/postfix/virtual_aliases
...
