---
- name: Ensure HAproxy present
  become: yes
  ansible.builtin.apt:
    name:
    - haproxy
    state: present
- name: Create/Update HAProxy SystemD service file
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/haproxy.service
    group: root
    mode: "0644"
    owner: root
    src: haproxy.service
  notify: Restart haproxy service
- name: Ensure private client certificate and key (for backends)
  ansible.builtin.include_tasks: task-cert_private_client.yml
- name: Ensure public client certificate and key (for external)
  ansible.builtin.include_tasks: task-cert_public_local_full.yml
- name: Ensure HAProxy configuration directory exists
  become: yes
  ansible.builtin.file:
    path: /etc/haproxy/haproxy.cfg.d
    group: root
    mode: "0750"
    owner: root
    state: directory
- name: Ensure HAProxy ACL files directory exists
  become: yes
  ansible.builtin.file:
    path: /etc/haproxy/acl-files
    group: root
    mode: "0750"
    owner: root
    state: directory
- name: Create/Update HAProxy configuration static files
  become: yes
  ansible.builtin.copy:
    dest: /etc/haproxy/haproxy.cfg.d/
    group: root
    mode: "0640"
    owner: root
    src: haproxy.cfg.d/
  notify: Restart haproxy
- name: Create HAProxy DHParam file
  become: yes
  ansible.builtin.template:
    dest: "{{ ha_dhparam_file }}"
    group: haproxy
    mode: "0640"
    owner: root
    src: dhparam.j2
  notify: Reload haproxy
- name: Add/Update HAProxy templated configuration
  become: yes
  loop:
  - 10-20-global-dh-param
  - 20-10-userlist-stats
  - 20-14-userlist-sogo
  - 50-10-frontends-http_s-main
  - 70-14-backends-sogo
  - 70-80-backends-webhost
  ansible.builtin.template:
    dest: /etc/haproxy/haproxy.cfg.d/{{ item }}.cfg
    group: root
    mode: "0640"
    owner: root
    src: haproxy.cfg.d/{{ item }}.cfg.j2
  notify: Reload haproxy
- name: Create/Update HAProxy ACL files
  become: yes
  loop:
  - mal_beg
  - mal_end
  - mal_sub
  - web_nowww
  - web_www
  ansible.builtin.template:
    dest: /etc/haproxy/acl-files/{{ item }}.txt
    group: root
    mode: "0640"
    owner: root
    src: acl-files/{{ item }}.txt.j2
  notify: Reload haproxy
- name: Add HAProxy AUTH Fail2Ban config
  become: yes
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.d/haproxy.local
    group: root
    mode: "0644"
    owner: root
    src: haproxy_jail.local
  notify: Restart Fail2Ban
- name: Configure firewall
  become: yes
  block:
  - name: Allow HTTP in on external interface
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      to_port: 80
    when: ansible_facts['default_ipv4'] is defined
  - name: Allow HTTPS in on external interface
    community.general.ufw:
      rule: allow
      interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
      direction: in
      proto: tcp
      to_port: 443
    when: ansible_facts['default_ipv4'] is defined
...
