---
- name: Configure postfix as an email sender (only to own server)
  become: yes
  block:
  - name: Ensure postfix is installed
    ansible.builtin.apt:
      name:
      - postfix
  - name: Configure postfix main.cf
    ansible.builtin.template:
      dest: /etc/postfix/main.cf
      group: root
      mode: "0644"
      owner: root
      src: main.cf.j2
    notify: Restart postfix
  - name: Configure postfix master.cf
    ansible.builtin.template:
      dest: /etc/postfix/master.cf
      group: root
      mode: "0644"
      owner: root
      src: master.cf.j2
    notify: Restart postfix
  - name: Configure sender addresses to only deliver locally
    ansible.builtin.template:
      dest: /etc/postfix/sender_default_transport_map
      group: root
      mode: "0644"
      owner: root
      src: sender_default_transport_map.j2
    notify: Rehash sender transport map
  - name: Configure virtual mailboxes
    ansible.builtin.template:
      dest: /etc/postfix/vmailbox
      group: root
      mode: "0644"
      owner: root
      src: vmailbox.j2
    notify: Rehash virtual mailboxes
  - name: Configure virtual aliases
    ansible.builtin.template:
      dest: /etc/postfix/virtual_aliases
      group: root
      mode: "0644"
      owner: root
      src: virtual_aliases.j2
    notify: Rehash virtual aliases
  - name: Configure system email aliases
    ansible.builtin.template:
      dest: /etc/aliases
      group: root
      mode: "0644"
      owner: root
      src: aliases.j2
    notify: Apply email aliases
    # yamllint disable rule:line-length
- name: Generate network/netmask for email_internal_senders
  ansible.builtin.command: echo "{{ item.network | quote }}/{{ item.netmask | quote }}"
  loop: "{{ internal_sender_ipv4 }}"
  vars:
    internal_sender_ipv4: "{{ ( groups['email_internal_senders'] | difference(groups['bare_metal'] )) | map('extract', hostvars, ['ansible_facts', 'ens3', 'ipv4'] ) }}"
  register: netaddr
  changed_when: false
- name: Allow localnet SMTP (alternate port)
  become: yes
  community.general.ufw:
    rule: allow
    interface: ens3
    direction: in
    proto: tcp
    src: "{{ item }}"
    dest: "{{ ansible_facts['ens3']['ipv4']['address'] }}"
    to_port: "{{ internal_relay_port }}"
  loop: "{{ internal_sender_cidrs }}"
  vars:
    internal_sender_netaddrs: "{{ netaddr.results | map(attribute='stdout') }}"
    internal_sender_cidrs: "{{ internal_sender_netaddrs | ansible.utils.ipaddr('net') | unique }}"
...
