---
- name: Configure postfix as an email receiver (internal only)
  become: yes
  block:
  - name: Ensure postfix is installed
    ansible.builtin.apt:
      name:
      - postfix
  - name: Configure postfix main.cf
    ansible.builtin.template:
      dest: /etc/postfix/main.cf
      group: root
      mode: "0644"
      owner: root
      src: main.cf.j2
    notify: Restart postfix
  - name: Configure postfix master.cf
    ansible.builtin.template:
      dest: /etc/postfix/master.cf
      group: root
      mode: "0644"
      owner: root
      src: master.cf.j2
    notify: Restart postfix
  - name: Configure sender addresses which should only deliver locally
    ansible.builtin.template:
      dest: /etc/postfix/sender_default_transport_map
      group: root
      mode: "0644"
      owner: root
      src: sender_default_transport_map.j2
    notify: Rehash sender transport map
  - name: Configure virtual mailboxes
    ansible.builtin.template:
      dest: /etc/postfix/vmailbox
      group: root
      mode: "0644"
      owner: root
      src: vmailbox.j2
    notify: Rehash virtual mailboxes
  - name: Configure virtual aliases
    ansible.builtin.template:
      dest: /etc/postfix/virtual_aliases
      group: root
      mode: "0644"
      owner: root
      src: virtual_aliases.j2
    notify: Rehash virtual aliases
  - name: Configure system email aliases
    ansible.builtin.template:
      dest: /etc/aliases
      group: root
      mode: "0644"
      owner: root
      src: aliases.j2
    notify: Apply email aliases
- name: Allow localnet SMTP (alternate port)
  become: yes
  community.general.ufw:
    rule: allow
    interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
    direction: in
    proto: tcp
    src: "{{ v4nat_net }}/{{ v4nat_prefix }}"
    to_port: "{{ internal_relay_port }}"
  when: ansible_facts['default_ipv4'] is defined
- name: Allow localnet6 SMTP (alternate port)
  become: yes
  community.general.ufw:
    rule: allow
    interface: "{{ ansible_facts['default_ipv6']['interface'] }}"
    direction: in
    proto: tcp
    src: "{{ v6nat_net }}/{{ v6nat_prefix }}"
    to_port: "{{ internal_relay_port }}"
  when: ansible_facts['default_ipv6'] is defined
...
