---
dependencies:
- role: service_apache2_conf
  vars:
    apache2_global_https_port: "{{ gdav_port }}"
- role: service_apache2_mod
  vars:
    apache2_global_cache_disk_path: /
    mods_noauth: false
    mods_service_add:
    - proxy
    - proxy_http
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Add SoGo and its requirements
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
