---
- name: Enable systemd-resolved
  become: yes
  ansible.builtin.systemd:
    name: systemd-resolved
    enabled: true
    state: started
- name: Configure systemd-resolved
  become: yes
  ansible.builtin.template:
    dest: /etc/systemd/resolved.conf
    group: root
    mode: "0644"
    owner: root
    src: resolved.conf.j2
  notify: Restart resolved
- name: Use resolved exclusively
  become: yes
  ansible.builtin.file:
    path: /etc/resolv.conf
    src: /run/systemd/resolve/stub-resolv.conf
    state: link
- name: Create DNSSEC trust anchors dir for resolved
  become: yes
  ansible.builtin.file:
    path: /etc/dnssec-trust-anchors.d
    group: root
    mode: "0755"
    owner: root
    state: directory
- name: Set non-DNSSEC rfc1618 domains for resolved
  become: yes
  ansible.builtin.copy:
    dest: /etc/dnssec-trust-anchors.d/rfc1618.negative
    group: root
    mode: "0644"
    owner: root
    src: rfc1618.negative
  notify: Restart resolved
- name: Set non-DNSSEC domains for resolved
  become: yes
  ansible.builtin.template:
    dest: /etc/dnssec-trust-anchors.d/localnets.negative
    group: root
    mode: "0644"
    owner: root
    src: localnets.negative.j2
  notify: Restart resolved
...
