---
# yamllint disable rule:key-ordering
stages:
- checks
- build

image:
  name: danielfdickinson/gitlab-debian-ansible-pre-commit:0.2.3

include:
- template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml

before_script:
- chmod 0700 .
- ansible --version
- ansible-lint --version

checks_a:
  stage: checks
  script:
  - chmod 0700 .
  - >
      pre-commit install --install-hooks
  - >
      pre-commit run --all-files
checks_b:
  stage: checks
  script:
  - chmod 0700 .
  - ansible-lint
...
