---
# yamllint disable rule:key-ordering
stages:
- checks
- build

image:
  name: danielfdickinson/gitlab-debian-packer-pre-commit:0.2.5

before_script:
- ansible --version

checks_a:
  rules:
  - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH =~ /^doci$/ # yamllint disable-line
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /doci$/ # yamllint disable-line
  stage: checks
  script:
  - >
      pre-commit install --install-hooks
  - >
      pre-commit run --all-files
# yamllint disable rule:line-length
# checks_b:
#   rules:
#   - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH =~ /^doci$/ # yamllint disable-line
#   - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^doci$/ # yamllint disable-line
#   stage: checks
#   script:
#   - ansible lint
...
