---
all:
  children:
    bastions:
      hosts:
        airlockddev.internal.dfd:
    edge_hosts:
      hosts:
        airlockddev.internal.dfd:
        gateddev.ddev:
    edgy_proxy_clients:
      hosts:
        imapddev.ddev:
    email_mxes:
      children:
        external_mxes:
          hosts:
            smtp01ddev.ddev:
        internal_mxes:
          hosts:
            imapddev.ddev:
    email_senders:
      children:
        email_external_senders:
          hosts:
            smtp01ddev.ddev:
        email_internal_senders:
          hosts:
            airlockddev.internal.dfd:
            gateddev.ddev:
            gdavddev.ddev:
            imapddev.ddev:
            wwwddev.ddev:
    groupware:
      hosts:
        gdavddev.ddev:
    mailbox_servers:
      hosts:
        imapddev.ddev:
    private_cert_ssl_servers:
      hosts:
        imapddev.ddev:
    reverse_proxies:
      children:
        rproxy_external:
          hosts:
            gateddev.ddev:
    website_servers:
      hosts:
        wwwddev.ddev:
...
