---
all:
  children:
    backup_clients:
      children:
        backup_clients_ovh:
          hosts: {}
          # airlockddev.internal.dfd:
          # gateddev.ddev:
          # gdavddev.ddev:
          # imapddev.ddev:
          # wwwddev.ddev:
    bare_metal:
      children:
        dual_interface_metal:
          hosts:
            dlcicl01.internal.dfd:
        libvirtd_hosts:
          hosts:
            dlcicl01.internal.dfd:
    cert_private_ssl_servers:
      hosts:
        imapddev.ddev:
    edge_hosts:
      children:
        bastions:
          hosts:
            airlockddev.ddev:
        external_services:
          hosts:
            imapddev.ddev:
            smtp01ddev.ddev:
        external_ssh:
          hosts:
            airlockddev.ddev:
            dlcicl01.internal.dfd:
        rproxy_external:
          hosts:
            gateddev.ddev:
    email_mxes:
      children:
        external_mxes:
          hosts:
            smtp01ddev.ddev:
        internal_mxes:
          hosts:
            imapddev.ddev:
    email_senders:
      children:
        email_external_senders:
          hosts:
            smtp01ddev.ddev:
        email_internal_senders:
          hosts:
            airlockddev.ddev:
            gateddev.ddev:
            gdavddev.ddev:
            imapddev.ddev:
            wwwddev.ddev:
    groupware:
      hosts:
        gdavddev.ddev:
    mailbox_servers:
      hosts:
        imapddev.ddev:
    rproxy_internal:
      hosts: {}
    storage_extra_local:
      hosts:
        dlcicl01.internal.dfd:
    website_servers:
      hosts:
        wwwddev.ddev:
...
