---
all:
  children:
    backup_clients:
      hosts: {}
    bare_metal:
      children:
        libvirtd_hosts:
          hosts:
            dlcicl01.internal.dfd:
    cert_private:
      children:
        ssl_private_clients:
          hosts:
            dlcicl01.internal.dfd:
            airlockldev.ldev:
            gateldev.ldev:
            gdavldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
            wwwldev.ldev:
        ssl_private_servers:
          hosts:
            gdavldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
            wwwldev.ldev:
    cert_public:
      children:
        public_full:
          # Uses a combined chain+cert+key file
          hosts:
            gateldev.ldev:
        ssl_public_servers:
          hosts:
            gateldev.ldev:
            imapldev.ldev:
            smtp01ldev.ldev:
    edge_hosts:
      children:
        bastions:
          hosts:
            airlockldev.ldev:
        bridge_second_interface:
          hosts:
            dlcicl01.internal.dfd:
        external_services:
          hosts:
            imapldev.ldev:
            smtp01ldev.ldev:
        external_ssh:
          hosts:
            airlockldev.ldev:
            dlcicl01.internal.dfd:
        local_ipv6:
          # RFC4193 internal static address (ULA) for testing local IPv6
          # when external IPv6 not available (on the outward facing interfaces)
          hosts:
            dlcicl01.internal.dfd:
        rproxy_external:
          hosts:
            gateldev.ldev:
    email_mxes:
      children:
        external_mxes:
          hosts:
            smtp01ldev.ldev:
        internal_mxes:
          hosts:
            imapldev.ldev:
    email_senders:
      children:
        email_external_senders:
          hosts:
            smtp01ldev.ldev:
        email_internal_senders:
          hosts:
            dlcicl01.internal.dfd:
            airlockldev.ldev:
            gateldev.ldev:
            gdavldev.ldev:
            imapldev.ldev:
            wwwldev.ldev:
    environments:
      children:
        bare_metal_local:
          hosts:
            dlcicl01.internal.dfd:
        non_public_env:
          # May be internet facing, but not using public certs
          children:
            ldev:
              hosts:
                airlockldev.ldev:
                gdavldev.ldev:
                imapldev.ldev:
                smtp01ldev.ldev:
                gateldev.ldev:
                wwwldev.ldev:
    groupware:
      hosts:
        gdavldev.ldev:
    host_locations:
      children:
        dfd_local:
          hosts:
            dlcicl01.internal.dfd:
        ovh_bhs:
          hosts: {}
        ovh_rbx:
          hosts: {}
    mailbox_servers:
      hosts:
        imapldev.ldev:
    rproxy_internal:
      hosts:
        gdavldev.ldev:
    storage_extra:
      hosts:
        dlcicl01.internal.dfd:
    website_servers:
      hosts:
        wwwldev.ldev:
...
