---
all:
  children:
    backup_clients:
      hosts: {}
    bare_metal:
      children:
        libvirtd_hosts:
          children:
            libvirtd_split_pools:
              hosts:
                dlcicl01.ldev.thecshore.ca:
            ldev_host:
              hosts:
                dlcicl01.ldev.thecshore.ca:
            kss_host: {}
            # cbay02.kss.thecshore.ca:
    cert_private:
      children:
        ssl_private_clients:
          hosts:
            dlcicl01.ldev.thecshore.ca:
        ssl_private_servers:
          hosts: {}
    cert_public:
      children:
        public_full:
          # Uses a combined chain+cert+key file
          hosts: {}
        ssl_public_servers:
          hosts: {}
    edge_hosts:
      children:
        bastions:
          hosts: {}
        bridge_second_interface:
          hosts:
            dlcicl01.ldev.thecshore.ca:
        external_services:
          hosts: {}
        external_ssh:
          hosts:
            dlcicl01.ldev.thecshore.ca:
        local_ipv6:
          # RFC4193 internal static address (ULA) for testing local IPv6
          # when external IPv6 not available (on the outward facing interfaces)
          hosts:
            dlcicl01.ldev.thecshore.ca:
        rproxy_external:
          hosts: {}
    email_mxes:
      children:
        external_mxes:
          hosts: {}
        internal_mxes:
          hosts: {}
    email_senders:
      children:
        email_external_senders:
          hosts: {}
        email_internal_senders:
          hosts:
            dlcicl01.ldev.thecshore.ca:
    environments:
      children:
        bare_metal_local:
          hosts:
            dlcicl01.ldev.thecshore.ca:
            # bare_metal_rbxks:
            #  hosts:
            #     cbay02.kss.thecshore.ca:
    groupware:
      hosts: {}
    host_locations:
      children:
        dfd_local:
          hosts:
            dlcicl01.ldev.thecshore.ca:
        ovh_bhs:
          hosts: {}
        ovh_rbx:
          hosts: {}
    mailbox_servers:
      hosts: {}
    rproxy_internal:
      hosts: {}
    storage_extra:
      hosts:
        dlcicl01.ldev.thecshore.ca:
    website_servers:
      hosts: {}
...
