---
- name: Ensure required variables are supplied on the command line
  hosts: bare_metal
  gather_facts: false
  tasks:
  - name: Ensure needed initialization variables are defined
    ansible.builtin.assert:
      that:
      - initial_ssh_port is defined
      - initial_password is defined
      - initial_ssh_user is defined
      quiet: true
      fail_msg: initial_ssh_port, initial_password, and initial_ssh_user must be defined
    vars:
      ansible_ssh_port: "{{ initial_ssh_port }}"
      ansible_become_password: "{{ initial_password }}"
      ansible_ssh_user: "{{ initial_ssh_user }}"
- name: Add admin user
  hosts: bare_metal
  gather_facts: true
  roles:
  - bare_metal_user_admin_add
  vars:
    new_admin_base_homedir: "{{ admin_base_homedir }}"
    new_admin_gecos: "{{ admin_gecos }}"
    new_admin_password: "{{ vault_admin_password }}"
    new_admin_ssh_key: "{{ vault_admin_ssh_key }}"
    new_admin_user: "{{ vault_admin_user }}"
    ansible_ssh_port: "{{ initial_ssh_port }}"
    ansible_become_password: "{{ initial_password }}"
    ansible_ssh_user: "{{ initial_ssh_user }}"

- name: Remove user 'debian' and set SSH port
  hosts: bare_metal
  roles:
  - bare_metal_user_debian_remove
  - bare_metal_system_sshd_port
  vars:
    ansible_ssh_port: "{{ initial_ssh_port }}"
    ansible_become_password: "{{ vault_ansible_become_password }}"
    ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
    new_ansible_port: "{{ vault_ansible_ssh_port }}"
...
