---
- name: Ensure required variables are supplied on the command line
  hosts: libvirtd_hosts
  gather_facts: false
  tasks:
  - name: Ensure given environment is valid
    ansible.builtin.assert:
      that:
      - envname is defined
      - (envname + '_host') in group_names
      quiet: true

- name: Add network for environment {{ (envname | default('')) + '_host' }}
  hosts: libvirtd_hosts:&{{ (envname | default('')) + '_host' }}
  gather_facts: true
  roles:
  - bare_metal_virt_env_network_add
  vars:
    net_domain: "{{ env_config_net[envname]['net_domain'] }}"
    v4nat_addr: "{{ env_config_net[envname]['v4nat_addr'] }}"
    v4nat_dhcp_end: "{{ env_config_net[envname]['v4nat_dhcp_end'] }}"
    v4nat_dhcp_start: "{{ env_config_net[envname]['v4nat_dhcp_start'] }}"
    v4nat_prefix: "{{ env_config_net[envname]['v4nat_prefix'] }}"
    v6nat_addr: "{{ env_config_net[envname]['v6nat_addr'] }}"
    v6nat_prefix: "{{ env_config_net[envname]['v6nat_prefix'] }}"
    vbridge: "{{ env_config_net[envname]['vbridge'] }}"
# After creating the network we need to gather facts again to pick-up the new
# network(s)
- name: Add access to libvirtd host chrony from guests
  hosts: libvirtd_hosts:&{{ (envname | default('')) + '_host' }}
  gather_facts: true
  roles:
  - bare_metal_virt_env_chronyd
  vars:
    v4nat_addr: "{{ env_config_net[envname]['v4nat_addr'] }}"
    v4nat_net: "{{ env_config_net[envname]['v4nat_net'] }}"
    v4nat_prefix: "{{ env_config_net[envname]['v4nat_prefix'] }}"
    v6nat_addr: "{{ env_config_net[envname]['v6nat_addr'] }}"
    v6nat_net: "{{ env_config_net[envname]['v6nat_net'] }}"
    v6nat_prefix: "{{ env_config_net[envname]['v6nat_prefix'] }}"

- name: Add port forwarding hooks for {{ (envname | default('')) + '_host' }}
  hosts: libvirtd_hosts:&{{ (envname | default('')) + '_host' }}
  gather_facts: true
  # Note that roles here must not interfere with other environments on the same
  # libvirtd_host
  roles:
  - bare_metal_virt_env_forward_hooks
  vars:
    domain_forwards: "{{ env_domain_forwards[envname] }}"
    guest_addrs: "{{ env_domain_addresses[envname] }}"
    v4host_addr: "{{ env_domain_addresses['bare_metal']['v4addr'] | default(None) }}"
    v6host_addr: "{{ env_domain_addresses['bare_metal']['v6addr'] | default(None) }}"
    vbridge: "{{ env_config_net[envname]['vbridge'] }}"

- name: Add guests for {{ (envname | default('')) + '_host' }}
  hosts: libvirtd_hosts:&{{ (envname | default('')) + '_host' }}
  roles:
  - bare_metal_virt_env_guests_add
...
