---
- hosts: dual_interface_metal
  roles:
  - network_bare_metal_dual_interface

# Expects the hosts files to be only for bare_metal hosts
- hosts: all
  gather_facts: true
  roles:
  - network_dns_use_resolved

- hosts: external_ssh
  roles:
  - user_bastion_user_add

- name: Include early plays which should be used on all hosts
  ansible.builtin.import_playbook: playbook-common-early.yml

- name: Include plays which define instances
  ansible.builtin.import_playbook: playbook-instances.yml
...
