---
- hosts: libvirtd_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - user_bastion_user_add
  - libvirtd_forward_hooks
  vars:
    libvirt_domain_forwards_map: "{{ libvirt_domain_ssh_forwards }}"

- hosts: bastions
  gather_facts: true
  any_errors_fatal: true
  roles:
  - user_bastion_user_add
  - packages_ssh_proxy

- hosts: all
  any_errors_fatal: true
  gather_facts: true
  roles:
  - user_admin_add_password

  # Must happen after an 'all' with gather_facts
- hosts: libvirtd_hosts
  roles:
  - libvirtd_forward_hooks
  - chronyd_libvirtd
  vars:
    libvirt_domain_forwards_map: "{{ libvirt_domain_forwards }}"

# Expects the hosts files to be for all hosts
- name: Include early plays which should be used on all hosts
  ansible.builtin.import_playbook: playbook-common-early.yml

- name: Include plays which define instances
  ansible.builtin.import_playbook: playbook-instances.yml
...
