---
- name: Ensure required variables are supplied on the command line
  hosts: libvirtd_hosts
  gather_facts: false
  tasks:
  - name: Ensure given environments are valid
    ansible.builtin.assert:
      that:
      - envname in group_names
      - guest_envname is defined
      quiet: true

- name: Add network for environment {{ envname | default([]) }}
  hosts: libvirtd_hosts:&{{ envname | default([]) }}
  gather_facts: true
  roles:
  - libvirtd_network_add
  vars:
    central_internal_domain: "{{ vault_env_conn_admin[guest_envname]['central_internal_domain'] }}"
    v4nat_addr: "{{ vault_env_conn_admin[guest_envname]['v4nat_addr'] }}"
    v4nat_cidr: "{{ vault_env_conn_admin[guest_envname]['v4nat_addr'] + '/' + ( vault_env_conn_admin[guest_envname]['v4nat_prefix'] | string ) }}"
    v4nat_prefix: "{{ vault_env_conn_admin[guest_envname]['v4nat_prefix'] }}"
    v6nat_addr: "{{ vault_env_conn_admin[guest_envname]['v6nat_addr'] }}"
    v6nat_cidr: "{{ vault_env_conn_admin[guest_envname]['v6nat_addr'] }}/64"
    v6nat_net: "{{ vault_env_conn_admin[guest_envname]['v6nat_net'] }}"
    v6nat_prefix: "64"
    vbridge: "{{ vault_env_conn_admin[guest_envname]['vbridge'] }}"

# After creating the network we need to gather facts again to pick-up the new
# network(s)
- name: Add access to libvirtd host chrony from guests
  hosts: libvirtd_hosts:&{{ envname | default([]) }}
  gather_facts: true
  roles:
  - chronyd_libvirtd
  vars:
    v4nat_addr: "{{ vault_env_conn_admin[guest_envname]['v4nat_addr'] }}"
    v4nat_net: "{{ vault_env_conn_admin[guest_envname]['v4nat_net'] }}"
    v4nat_prefix: "{{ vault_env_conn_admin[guest_envname]['v4nat_prefix'] }}"
    v6nat_addr: "{{ vault_env_conn_admin[guest_envname]['v6nat_addr'] }}"
    v6nat_net: "{{ vault_env_conn_admin[guest_envname]['v6nat_net'] }}"
    v6nat_prefix: "{{ vault_env_conn_admin[guest_envname]['v6nat_prefix'] }}"

- name: Add port forwarding hooks for {{ envname | default([]) }}
  hosts: libvirtd_hosts:&{{ envname | default([]) }}
  gather_facts: true
  # Note that roles here must not interfere with other environments on the same
  # libvirtd_host
  roles:
  - libvirtd_forward_hooks
  vars:
    guest_data: "{{ libvirt_guest_definitions | selectattr('envname', 'equalto', guest_envname) }}"
    vbridge: "{{ vault_env_conn_admin[guest_envname]['vbridge'] }}"

- name: Add guests for {{ envname | default([]) }}
  hosts: libvirtd_hosts:&{{ envname | default([]) }}
  roles:
  - libvirtd_guests_add
  vars:
    libvirt_pool_base_images: "{{ host_libvirt_pool_base_images }}"
    libvirt_pool_base_images_path: "{{ host_libvirt_pool_base_images_path }}"
    libvirt_pool_cloud_init: "{{ host_libvirt_pool_cloud_init }}"
    libvirt_pool_cloud_init_path: "{{ host_libvirt_pool_cloud_init_path }}"
...
