---
- hosts: libvirtd_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - user_bastion_user_add
  - libvirtd_forward_hooks_external_ssh

- hosts: bastions
  gather_facts: true
  any_errors_fatal: true
  roles:
  - user_bastion_user_add
  - packages_ssh_proxy

- hosts: all
  gather_facts: true
  roles:
  - user_admin_add_password

# Expects the hosts files to be for all hosts
- name: Include early plays which should be used on all hosts
  ansible.builtin.import_playbook: playbook-common-early.yml

- name: Include plays which define instances
  ansible.builtin.import_playbook: playbook-instances.yml
...
