---
- hosts: all
  gather_facts: true
  roles:
  - user_admin_add_password

# Expects the hosts files to be for all hosts
- name: Include early plays which should be used on all hosts
  ansible.builtin.import_playbook: playbook-common-early.yml

- name: Include plays which define instances
  ansible.builtin.import_playbook: playbook-instances.yml
...
