---
- hosts: bare_metal
  gather_facts: true
  roles:
  - network_dns_use_resolved

- hosts: bare_metal:&local_ipv6
  roles:
  - network_local_ipv6

- hosts: bare_metal:&dual_interface
  roles:
  - network_bare_metal_dual_interface

- hosts: bare_metal:&storage_extra
  roles:
  - storage_setup_extra_bare_metal

- hosts: bare_metal
  roles:
  - packages_base
  - packages_bare_metal
  - packages_firmware

- hosts: bare_metal:&backup_clients_ovh
  roles:
  - packages_backup_ovh

- hosts: libvirtd_hosts
  roles:
  - libvirtd
  - user_libvirt_client_add
  - fail2ban
  - fail2ban_ssh
  - postfix_sender_internal
  - user_bastion_user_add
...
