---
- name: Include bastions playbook (which can also be standalone)
  ansible.builtin.import_playbook: playbook-env-bastions.yml

- name: Include instances base playbook (which can also be standalone)
  ansible.builtin.import_playbook: playbook-env-instances_base.yml

- name: Include mail server plays (which can also be standalone)
  ansible.builtin.import_playbook: playbook-env-mail_servers.yml

- name: Include websites and reverse proxy playbook (which can also be standalone)
  ansible.builtin.import_playbook: playbook-env-web_external.yml

- name: Include plays common to all instances (which can also be standalone)
  ansible.builtin.import_playbook: playbook-env-instances_common.yml
...
