---
- name: Ensure required variables are supplied on command line
  hosts: bastions
  gather_facts: false
  pre_tasks:
  - name: Ensure given environment is valid
    ansible.builtin.assert:
      that:
      - envname in group_names
      quiet: true
      fail_msg: "{{ envname | quote }} is not a valid envname (environment)"

- name: Wait for cloud init to finish
  hosts: bastions
  tasks:
  - name: Check cloud init status
    community.general.cloud_init_data_facts:
      filter: status
    register: cistat
    until: cistat.cloud_init_data_facts.status.v1.stage is defined and not cistat.cloud_init_data_facts.status.v1.stage
    retries: 50
    delay: 5
  - name: Ensure cloud init result was success
    community.general.cloud_init_data_facts:
      filter: status
    register: res
    failed_when: res.cloud_init_data_facts.status.v1.errors is defined and res.cloud_init_data_facts.status.v1.errors
    changed_when: false

- name: Configure bastions in order to access other guests
  hosts: bastions
  gather_facts: true
  roles:
  - packages_base
  - user_bastion_user_add
  - packages_ssh_proxy
  - system_fail2ban_ssh
  - packages_firmware
...
