---
- hosts: dlcicl01.internal.dfd
  gather_facts: true
  any_errors_fatal: true
  roles:
  - libvirtd_network_add

# After creating the network we need to gather facts again to pick-up the new
# network(s)
- hosts: libvirtd_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - chronyd_libvirtd

...
