---
- name: Ensure required variables are supplied on the command line
  hosts: bare_metal
  gather_facts: false
  pre_tasks:
  - name: Ensure given environment is valid
    ansible.builtin.assert:
      that:
      - envname in group_names
      quiet: true
      fail_msg: "{{ envname | quote }} is not a valid envname (environment)"

- name: Configure name resolution
  hosts: bare_metal
  gather_facts: true
  roles:
  - network_hosts_fqdn_real_ip
  - network_dns_use_resolved

- name: Add local ipv6 when no internet-ipv6 available
  hosts: bare_metal:&local_ipv6
  roles:
  - network_local_ipv6

- name: Make second interface a bridge
  hosts: bare_metal:&bridge_second_interface
  roles:
  - network_bridge_second_interface

- name: Setup additional storage
  hosts: bare_metal:&storage_extra
  roles:
  - storage_setup_extra

- name: Add base and hardware packages
  hosts: bare_metal
  roles:
  - packages_base
  - packages_bare_metal
  - packages_firmware

- name: Configure restic backup for local instances
  hosts: bare_metal:&backup_clients:&dfd_local
  roles:
  - backup_restic

- name: Configure restic backup for OVH (BHS) instances
  hosts: bare_metal:&backup_clients:&ovh_bhs
  roles:
  - backup_ovh
  - backup_restic

- name: Add Libvirt, guests, and enable Fail2Ban
  hosts: bare_metal:&libvirtd_hosts
  roles:
  - libvirtd
  - user_libvirt_client_add
  - system_fail2ban
  - system_fail2ban_ssh

- name: Add NUT to local bare-metal
  hosts: bare_metal:&bare_metal_local
  roles:
  - service_hardware_upsd
...
