---
- name: Configure name resolution
  hosts: bare_metal
  gather_facts: true
  roles:
  - bare_metal_network_hosts_file
  - bare_metal_network_resolved

- name: Add local ipv6 when no internet-ipv6 available
  hosts: bare_metal:&local_ipv6
  roles:
  - bare_metal_network_ipv6
  vars:
    local_ipv6_cidr: "{{ env_domain_addresses['bare_metal']['v6addr'] }}/{{ env_domain_addresses['bare_metal']['v6prefix'] }}"
    local_ipv6_gateway: "{{ env_domain_addresses['bare_metal']['v6gateway'] }}"

- name: Make second interface a bridge
  hosts: bare_metal:&bridge_second_interface
  roles:
  - bare_metal_network_bridge_second_interface

- name: Setup additional storage
  hosts: bare_metal:&storage_extra
  roles:
  - bare_metal_system_storage_extra

- name: Add base and hardware packages
  hosts: bare_metal
  roles:
  - system_base
  - bare_metal_packages_base
  - packages_firmware

- name: Configure restic backup for local instances
  hosts: bare_metal:&backup_clients:&dfd_local
  roles:
  - backup_restic

- name: Configure restic backup for OVH (BHS) instances
  hosts: bare_metal:&backup_clients:&ovh_bhs
  roles:
  - backup_ovh
  - backup_restic

- name: Add Libvirt, guests, and enable Fail2Ban
  hosts: bare_metal:&libvirtd_hosts
  roles:
  - bare_metal_service_libvirtd
  - bare_metal_user_libvirt_client_add
  - system_fail2ban_ssh

- name: Add split Libvirt pools on certain hosts
  hosts: bare_metal:&libvirtd_split_pools
  roles:
  - bare_metal_service_libvirtd_pools

- name: Add NUT to local bare-metal
  hosts: bare_metal:&bare_metal_local
  roles:
  - bare_metal_service_upsd
...
