---
- hosts: libvirtd_hosts
  roles:
  - user_libvirt_client_add
- hosts: mailbox_servers
  roles:
  - dovecot
- hosts: internal_mxes
  roles:
  - postfix_mx_internal
- hosts: email_internal_senders:!internal_mxes
  roles:
  - postfix_sender_internal
- hosts: rproxy_external
  roles:
  - reverse_proxy_external
- hosts: website_servers:rproxy_internal
  roles:
  - apache2_proxy_protocol
...
