---
- name: Configure name resolution
  hosts: bare_metal
  gather_facts: true
  roles:
  - danielfdickinson.system_base_debian.network_hosts_file
  - network_resolved

- name: Make second interface a bridge
  hosts: bare_metal:&bridge_second_interface
  roles:
  - network_bridge_second_interface

- name: Add local ipv6 when no internet-ipv6 available
  hosts: bare_metal:&local_ipv6
  gather_facts: true
  pre_tasks:
  - name: Gather facts (primary interface may have changed)
    ansible.builtin.setup:
  roles:
  - network_ipv6
  vars:
    local_ipv6_cidr: "{{ env_domain_addresses['bare_metal']['v6addr'] }}/{{ env_domain_addresses['bare_metal']['v6prefix'] }}"
    local_ipv6_gateway: "{{ env_domain_addresses['bare_metal']['v6gateway'] }}"

- name: Setup additional storage
  hosts: bare_metal:&storage_extra
  roles:
  - system_storage_extra

- name: Add base and hardware packages
  hosts: bare_metal
  gather_facts: true
  pre_tasks:
  - name: Gather facts (primary interface may have changed)
    ansible.builtin.setup:
  roles:
  - danielfdickinson.system_base_debian.dfd_base_misc
  - danielfdickinson.system_base_debian.ufw
  - danielfdickinson.system_base_debian.fail2ban
  - role: danielfdickinson.system_base_debian.firmware_install
    firmware_extra:
    - firmware-realtek
  tasks:
  - name: Ensure smartmontools is installed
    become: yes
    ansible.builtin.apt:
      name:
      - smartmontools
      state: present

- name: Add libvirt and a user for remote libvirt access
  hosts: bare_metal:&libvirtd_hosts
  roles:
  - service_libvirtd
  - role: danielfdickinson.system_base_debian.user_add_other_base
    new_base_homedir: "{{ admin_base_homedir }}"
    new_user: "{{ libvirt_client_user}}"
    new_user_ssh_key: "{{ libvirt_client_ssh_key }}"
    new_users_groups:
    - libvirt

- name: Add split libvirt pools on certain hosts
  hosts: bare_metal:&libvirtd_split_pools
  roles:
  - service_libvirtd_pools

- name: Add NUT to local bare-metal
  become: yes
  hosts: bare_metal:&bare_metal_local
  roles:
  - maxhoesel.nut_netclient
...
