---
- name: Ensure required variables are supplied on command line
  hosts: website_servers
  gather_facts: false
  pre_tasks:
  - name: Ensure given environment is valid
    ansible.builtin.assert:
      that:
      - envname in group_names
      quiet: true
      fail_msg: "{{ envname | quote }} is not a valid envname (environment)"

- name: Configure website servers (including limited rsyncd for site deploys)
  hosts: website_servers
  roles:
  - apache2_webhost_static

- name: Configure groupware
  hosts: groupware
  roles:
  - sogo

- name: Configure website and internal reverse proxies to use PROXY protocol
  hosts: website_servers:rproxy_internal
  roles:
  - apache2_proxy_protocol

- name: Configure external (edge) reverse proxy
  hosts: rproxy_external
  roles:
  - haproxy
...
