---
- name: Add public server certificates to system
  become: yes
  block:
  - name: Add directory for public certificates and keys
    ansible.builtin.file:
      group: root
      mode: "0755"
      owner: root
      path: /etc/ssl/pubcert
      state: directory
  - name: Add public server certificate as file
    ansible.builtin.copy:
      dest: "{{ host_public_cert_cert_file }}"
      group: root
      mode: "0644"
      owner: root
      src: "{{ host_public_cert_cert_file_src }}"
    when: host_public_cert_cert_file is defined
  - name: Add key for public cert as file
    ansible.builtin.copy:
      dest: "{{ host_public_cert_key_file }}"
      group: root
      mode: "0600"
      owner: root
      src: "{{ host_public_cert_key_file_src }}"
    when: host_public_cert_key_file is defined
  - name: Add cert+key for public cert as file
    ansible.builtin.template:
      dest: "{{ host_public_cert_full_file }}"
      group: root
      mode: "0600"
      owner: root
      src: public_cert_full_file.j2
    when: host_public_cert_full_file is defined
...
