---
dependencies:
- role: system_cert_client_private
- role: system_cert_server_private
- role: system_cert_public
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure dovecot as mailbox server (IMAP) and Submission relay
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
