---
dependencies:
- role: system_cert_client_private
- role: system_cert_server_private
- role: system_cert_public
- role: system_fail2ban
  vars:
    f2b_jails:
    - content: "{{ lookup('file', 'dovecot_jail.local') }}"
      dest: dovecot
- role: packages_dovecot
- role: service_postfix_mx_internal
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure dovecot as mailbox server (IMAP) and Submission relay
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
