---
- name: Add and configure admin user
  become: yes
  block:
  - name: Ensure homedir is recognized by apparmor
    ansible.builtin.copy:
      dest: /etc/apparmor.d/tunables/home.d/local-home.site.local
      group: root
      mode: "0644"
      owner: root
      src: local-home.site.local
    notify: Reload apparmor
  - name: Add admin_user
    ansible.builtin.user:
      name: "{{ vault_admin_user }}"
      comment: "{{ vault_admin_gecos }}"
      groups:
      - adm
      - sudo
      - sys
      home: /local-home/{{ vault_admin_user }}
      password: "{{ vault_admin_password }}"
      password_lock: false
      shell: /bin/bash
      state: present
    notify: Restart SSH server
  - name: Lockdown admin home dir
    ansible.builtin.file:
      path: /local-home/{{ vault_admin_user }}
      group: "{{ vault_admin_user }}"
      mode: "0700"
      owner: "{{ vault_admin_user }}"
      state: directory
  - name: Lockdown admin ssh dir
    ansible.builtin.file:
      path: /local-home/{{ vault_admin_user }}/.ssh
      group: "{{ vault_admin_user }}"
      mode: "0700"
      owner: "{{ vault_admin_user }}"
      state: directory
  - name: Add admin incoming public key
    ansible.builtin.copy:
      dest: /local-home/{{ vault_admin_user }}/.ssh/authorized_keys
      content: "{{ vault_admin_ssh_key }}"
      group: "{{ vault_admin_user }}"
      mode: "0600"
      owner: "{{ vault_admin_user }}"
...
