---
- name: Add and configure admin user
  become: yes
  block:
  - name: Ensure required vars are defined
    ansible.builtin.assert:
      that:
      - new_admin_base_homedir is defined
      - new_admin_password is defined
      - new_admin_ssh_key is defined
      - new_admin_user is defined
      quiet: true
  - name: Add admin_user
    ansible.builtin.user:
      name: "{{ new_admin_user }}"
      comment: "{{ new_admin_gecos }}"
      groups:
      - adm
      - sudo
      - sys
      home: "{{ new_admin_base_homedir }}/{{ new_admin_user }}"
      password: "{{ new_admin_password }}"
      password_lock: false
      shell: /bin/bash
      state: present
    notify: Restart SSH server
  - name: Lockdown admin home dir
    ansible.builtin.file:
      path: "{{ new_admin_base_homedir }}/{{ new_admin_user }}"
      group: "{{ new_admin_user }}"
      mode: "0700"
      owner: "{{ new_admin_user }}"
      state: directory
  - name: Lockdown admin ssh dir
    ansible.builtin.file:
      path: "{{ new_admin_base_homedir }}/{{ new_admin_user }}/.ssh"
      group: "{{ new_admin_user }}"
      mode: "0700"
      owner: "{{ new_admin_user }}"
      state: directory
  - name: Add admin incoming public key
    ansible.builtin.template:
      dest: "{{ new_admin_base_homedir }}/{{ new_admin_user }}/.ssh/authorized_keys"
      group: "{{ new_admin_user }}"
      mode: "0600"
      owner: "{{ new_admin_user }}"
      src: authorized_keys.j2
...
