---
dependencies:
- role: system_clamav
- role: packages_clamav_milter
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Meta package to configure clamav-milter for use with postfix
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
