---
dependencies:
- role: apache2_proxy_protocol
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure Apache2 as a static webhost
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
