---
dependencies:
- role: apparmor_admin_homedir
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Add admin user
  license: MIT
  min_ansible_version: 2.14.1
  platforms:
  - name: Debian
    versions:
    - all
...
