---
- name: Install dependencies for radicale
  become: yes
  ansible.builtin.apt:
    name:
    - apache2-utils
    - python3
    - python3-bcrypt
    - python3-pip
    state: present
- name: Install radicale
  become: yes
  block:
  - name: Create user radicale
    ansible.builtin.user:
      name: radicale
      home: /var/lib/radicale
      password_lock: true
      shell: /usr/sbin/nologin
      state: present
      system: true
  - name: Ensure Radicale data dir is owned by radicale user
    ansible.builtin.file:
      path: /var/lib/radicale
      group: radicale
      mode: "0750"
      owner: radicale
      state: directory
  - name: Ensure Radicale collections dir exists and is owned by radicale user
    ansible.builtin.file:
      path: /var/lib/radicale/collections
      group: radicale
      mode: "0750"
      owner: radicale
      recurse: true
      state: directory
  - name: Ensure Radicale config dir exists
    ansible.builtin.file:
      path: /etc/radicale
      group: root
      mode: "0755"
      owner: root
      state: directory
  - name: Ensure Radicale log dir exists
    ansible.builtin.file:
      path: /var/log/radicale
      group: adm
      mode: "0750"
      owner: radicale
      state: directory
  - name: Ensure Radicale log file exists
    ansible.builtin.file:
      path: /var/log/radicale/radicale.log
      group: adm
      mode: "0640"
      owner: radicale
      state: file
    notify: Restart Radicale
  - name: Make hard link to private cert that Radicale can read
    ansible.builtin.file:
      path: "{{ host_private_cert_key_file }}-radicale"
      group: radicale
      mode: "0640"
      owner: root
      src: "{{ host_private_cert_key_file }}"
      state: hard
  - name: Do install of Radicale and RadicaleInfCloud
    ansible.builtin.command:
      argv: [python3, -m, pip, install, --upgrade, "https://gitlab.com/danielfdickinson/Unrud-RadicaleInfCloud/-/archive/master/Unrud-RadicaleInfCloud-master.tar.gz"]
    register: radicale_install_out
    changed_when: "'Successfully installed Radicale-InfCloud' in radicale_install_out.stdout"
    notify: Restart Radicale
  - name: Add Radicale main config
    ansible.builtin.template:
      dest: /etc/radicale/config
      group: root
      mode: "0644"
      owner: root
      src: radicale-config.j2
    notify: Restart Radicale
  - name: Add Radicale SystemD unit file
    ansible.builtin.copy:
      dest: /etc/systemd/system/radicale.service
      group: root
      mode: "0644"
      owner: root
      src: radicale.service
    notify: Enable and start Radicale
- name: Allow requests to Radicale in on external interface
  become: yes
  community.general.ufw:
    rule: allow
    interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
    direction: in
    proto: tcp
    to_port: "{{ libvirt_guest_definitions[envname][(env_guest_userdata[envname] | dict2items | selectattr('value.fqdn', 'equalto', inventory_hostname)).0.key]['gdav_port'] }}"
  when: ansible_facts['default_ipv4'] is defined
...
