---
- name: Ensure required variables are supplied on command line
  hosts: cert_private:cert_public
  gather_facts: false
  pre_tasks:
  - name: Ensure given environment is valid
    ansible.builtin.assert:
      that:
      - envname in group_names
      quiet: true
      fail_msg: "{{ envname | quote }} is not a valid envname (environment)"

- name: Add SSL private client certificate
  hosts: cert_private:&ssl_private_clients
  roles:
  - cert_private_client

- name: Add SSL private server certificate
  hosts: cert_private:&ssl_private_servers
  roles:
  - cert_private_server

- name: Use cert+key from certbot dns-01 (via local)
  # This avoids the need to do have/use certbot on the remote hosts
  # but we do need to push the renewed certificates from time to time
  hosts: cert_public
  roles:
  - cert_public_local_full
...
