---
- name: Configure Libvirt shutdown guest handling
  become: yes
  ansible.builtin.copy:
    dest: /etc/default/libvirt-guests
    group: root
    mode: "0644"
    owner: root
    src: libvirt-guests
...
