---
- name: Prevent freshclam install from modifying our configuration
  ansible.builtin.copy:
    content: conf_force_conffold=YES
    dest: /etc/ucf.conf
    group: root
    mode: "0644"
    owner: root
  when: local_freshclam_mirror is defined
- name: Ensure clamav directory exists
  become: yes
  ansible.builtin.file:
    path: /etc/clamav
    group: root
    mode: "0755"
    owner: root
    state: directory
  when: local_freshclam_mirror is defined
- name: Create freshclam configuration that uses private mirror
  # Note that use of a https://pypi.org/project/cvdupdate/ private
  # mirror is recommended during testing to avoid being rate limited.
  become: yes
  ansible.builtin.template:
    dest: /etc/clamav/freshclam.conf
    group: root
    mode: "0644"
    owner: root
    src: freshclam.conf.j2
  when: local_freshclam_mirror is defined
- name: Ensure clamav-daemon is installed
  become: yes
  ansible.builtin.apt:
    name:
    - clamav-daemon
    - clamav-freshclam
- name: Update freshclam service to fix systemd warning on start
  become: yes
  notify: Update clamav unit files and restart them
  ansible.builtin.copy:
    dest: /etc/systemd/system/clamav-freshclam.service
    group: root
    mode: "0644"
    owner: root
    src: clamav-freshclam.service
- name: Update clamav-daemon service to fix systemd warning on start
  become: yes
  notify: Update clamav unit files and restart them
  ansible.builtin.copy:
    dest: /etc/systemd/system/clamav-daemon.service
    group: root
    mode: "0644"
    owner: root
    src: clamav-daemon.service
...
