---
- name: Add directory for public certificates and keys
  become: yes
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/ssl/pubcert
    state: directory
- name: Add public server certificate as file
  become: yes
  ansible.builtin.copy:
    dest: "{{ host_public_cert_cert_file }}"
    group: root
    mode: "0644"
    owner: root
    src: "{{ host_public_cert_cert_file_src }}"
  when: host_public_cert_cert_file is defined
  notify:
  - Restart SSL-based server
- name: Add key for public cert as file
  become: yes
  ansible.builtin.copy:
    dest: "{{ host_public_cert_key_file }}"
    group: root
    mode: "0600"
    owner: root
    src: "{{ host_public_cert_key_file_src }}"
  when: host_public_cert_key_file is defined
  notify:
  - Restart SSL-based server
- name: Add cert+key for public cert as file
  become: yes
  ansible.builtin.template:
    dest: "{{ host_public_cert_full_file }}"
    group: root
    mode: "0600"
    owner: root
    src: public_cert_full_file.j2
  when: host_public_cert_full_file is defined
  notify:
  - Restart SSL-based server
...
