---
- name: Ensure postfix is installed
  become: yes
  ansible.builtin.apt:
    name:
    - postfix
- name: Ensure private CA certificate (for verifying internal MX) is present
  ansible.builtin.import_tasks: task-cert_private_ca.yml
  notify: Restart postfix
- name: Ensure private client certificate and key (for sending to internal MX)
  ansible.builtin.import_tasks: task-cert_private_client.yml
  notify: Restart postfix
- name: Configure email aliases
  become: yes
  ansible.builtin.template:
    dest: /etc/aliases
    group: root
    mode: "0644"
    owner: root
    src: aliases.j2
  notify: Apply email aliases
- name: Configure postfix main.cf
  become: yes
  ansible.builtin.template:
    dest: /etc/postfix/main.cf
    group: root
    mode: "0644"
    owner: root
    src: main.cf.j2
  notify: Restart postfix
- name: Configure postfix servers (master.cf)
  become: yes
  ansible.builtin.copy:
    dest: /etc/postfix/master.cf
    group: root
    mode: "0644"
    owner: root
    src: master.cf
  notify: Restart postfix
...
