---
- name: Restart SSH server
  become: yes
  ansible.builtin.service:
    name: ssh
    state: restarted
- name: Reload apparmor
  become: yes
  ansible.builtin.service:
    name: apparmor
    state: reloaded
...
