---
- name: Apply email aliases
  become: yes
  ansible.builtin.command: newaliases
- name: Restart postfix
  listen: Restart SSL-based server
  become: yes
  ansible.builtin.systemd:
    name: postfix
    state: restarted
...
