---
- name: Create temporary file
  become: yes
  ansible.builtin.tempfile:
    state: file
  register: snakeoil_full_temp
  changed_when: false
- name: Copy snakeoil cert and key to temporary file
  become: yes
  ansible.builtin.shell: cat /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key >> {{ snakeoil_full_temp.path }}
  when: snakeoil_full_temp.path is defined
  changed_when: false
- name: Copy combined file to final destination
  become: yes
  ansible.builtin.copy:
    dest: "{{ host_public_cert_full_file }}"
    group: root
    mode: "0640"
    owner: root
    remote_src: true
    src: "{{ snakeoil_full_temp.path }}"
  when: snakeoil_full_temp.path is defined
- name: Remove temporary file
  become: yes
  ansible.builtin.file:
    path: "{{ snakeoil_full_temp.path }}"
    state: absent
  when: snakeoil_full_temp.path is defined
  changed_when: false
...
