---
admin_base_homedir: "{{ env_conn_admin[envname]['admin_base_homedir'] }}"
admin_gecos: "{{ env_conn_admin[envname]['admin_gecos'] }}"
admin_password: "{{ env_conn_admin[envname]['admin_password'] }}"
admin_ssh_key: "{{ env_conn_admin[envname]['admin_ssh_key'] }}"
admin_ssh_key_userdata: "{{ env_conn_admin[envname]['admin_ssh_key_userdata'] }}"
admin_user: "{{ env_conn_admin[envname]['admin_user'] }}"
ansible_become_password: "{{ env_conn_admin[envname]['ansible_become_password'] }}"
ansible_ssh_common_args: "{% if 'external_ssh' not in group_names %}-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -p {{ bastion_port }} -W %h:%p -q {{ bastion_user }}@{{ bastion_host }}\"{% endif %}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_port: "{{ env_conn_admin[envname]['ansible_ssh_port'] }}"
ansible_ssh_user: "{{ env_conn_admin[envname]['ansible_ssh_user'] }}"
backupmx_port: "{{ vault_backupmx_port }}"
bastion_host: "{{ env_conn_admin[envname]['bastion_host'] }}"
bastion_ssh_key: "{{ env_conn_admin[envname]['bastion_ssh_key'] }}"
bastion_user: "{{ env_conn_admin[envname]['bastion_user'] }}"
central_local_domain: "{{ env_conn_admin[envname]['central_local_domain'] }}"
central_local_email: "{{ env_conn_admin[envname]['central_local_email'] }}"
default_mail_local_destinations: "{{ vault_default_mail_local_destinations }}"
dovecot_health_check_port: "{{ vault_dovecot_health_check_port }}"
env_conn_admin:
  bare_metal_local:
    admin_base_homedir: &default_admin_base_homedir /local-home
    admin_gecos: "{{ vault_env_conn_admin['bare_metal_local']['admin_gecos'] }}"
    admin_password: "{{ vault_env_conn_admin['bare_metal_local']['admin_password'] }}"
    admin_ssh_key: "{{ vault_env_conn_admin['bare_metal_local']['admin_ssh_key'] }}"
    admin_ssh_key_userdata: "{{ vault_env_conn_admin['bare_metal_local']['admin_ssh_key_userdata'] }}"
    admin_user: "{{ vault_env_conn_admin['bare_metal_local']['admin_user'] }}"
    ansible_become_password: "{{ vault_env_conn_admin['bare_metal_local']['ansible_become_password'] }}"
    ansible_ssh_port: "{{ host_ansible_ssh_port | default(22) }}"
    ansible_ssh_user: "{{ vault_env_conn_admin['bare_metal_local']['ansible_ssh_user'] }}"
    bastion_host: "{{ vault_env_conn_admin['bare_metal_local']['bastion_host'] }}"
    bastion_port: omit
    bastion_user: "{{ vault_env_conn_admin['bare_metal_local']['bastion_user'] }}"
    bastion_ssh_key: "{{ vault_env_conn_admin['bare_metal_local']['bastion_ssh_key'] }}"
    central_local_domain: &main_central_local_domain ldev
    central_local_email: "{{ vault_env_conn_admin['bare_metal_local']['central_local_email'] }}"
    external_rfc1618_domain: "{{ vault_env_conn_admin['bare_metal_local']['external_rfc1618_domain'] }}"
    fallback_dns: "{{ vault_env_conn_admin['bare_metal_local']['fallback_dns'] }}"
    internal_domain: &main_internal_domain ldev
    internal_relay_port: "{{ vault_env_conn_admin['bare_metal_local']['internal_relay_port'] }}"
    libvirt_client_ssh_key: "{{ vault_env_conn_admin['bare_metal_local']['libvirt_client_ssh_key'] }}"
    libvirt_client_user: "{{ vault_env_conn_admin['bare_metal_local']['libvirt_client_user'] }}"
    local_ipv6_cidr: "{{ host_local_ipv6_cidr | default(omit) }}"
    local_ipv6_gateway: "{{ host_local_ipv6_gateway | default(omit) }}"
    remote_admin_ip: "{{ vault_env_conn_admin['bare_metal_local']['remote_admin_ip'] }}"
    remote_monitoring_ips: "{{ vault_env_conn_admin['bare_metal_local']['remote_monitoring_ips'] }}"
    v6natnet_ula: "{{ vault_env_conn_admin['bare_metal_local']['v6natnet_ula'] }}"
  ldev:
    admin_base_homedir: *default_admin_base_homedir
    admin_gecos: "{{ vault_env_conn_admin['ldev']['admin_gecos'] }}"
    admin_password: "{{ vault_env_conn_admin['ldev']['admin_password'] }}"
    admin_ssh_key: "{{ vault_env_conn_admin['ldev']['admin_ssh_key'] }}"
    admin_ssh_key_userdata: "{{ vault_env_conn_admin['ldev']['admin_ssh_key_userdata'] }}"
    admin_user: "{{ vault_env_conn_admin['ldev']['admin_user'] }}"
    ansible_become_password: "{{ vault_env_conn_admin['ldev']['ansible_become_password'] }}"
    ansible_ssh_port: "{{ host_ansible_ssh_port | default(22) }}"
    ansible_ssh_user: "{{ vault_env_conn_admin['ldev']['ansible_ssh_user'] }}"
    bastion_host: "{{ vault_env_conn_admin['ldev']['bastion_host'] }}"
    bastion_port: &default_bastion_port "{{ host_bastion_ssh_port | default(22) }}"
    bastion_user: "{{ vault_env_conn_admin['ldev']['bastion_user'] }}"
    bastion_ssh_key: "{{ vault_env_conn_admin['ldev']['bastion_ssh_key'] }}"
    central_local_domain: *main_central_local_domain
    central_local_email: "{{ vault_env_conn_admin['ldev']['central_local_email'] }}"
    external_rfc1618_domain: "{{ vault_env_conn_admin['ldev']['external_rfc1618_domain'] }}"
    fallback_dns: "{{ vault_env_conn_admin['ldev']['fallback_dns'] }}"
    guest_ansible_ssh_port: "{{ vault_env_conn_admin['ldev']['guest_ansible_ssh_port'] }}"
    internal_domain: *main_internal_domain
    internal_relay_port: "{{ vault_env_conn_admin['ldev']['internal_relay_port'] }}"
    libvirt_client_ssh_key: omit
    libvirt_client_user: omit
    local_ipv6_cidr: omit
    local_ipv6_gateway: omit
    remote_admin_ip: "{{ vault_env_conn_admin['ldev']['remote_admin_ip'] }}"
    remote_monitoring_ips: "{{ vault_env_conn_admin['ldev']['remote_monitoring_ips'] }}"
    v4nat_addr: "{{ vault_env_conn_admin['ldev']['v4nat_addr'] }}"
    v4nat_net: "{{ vault_env_conn_admin['ldev']['v4nat_net'] }}"
    v4nat_prefix: "{{ vault_env_conn_admin['ldev']['v4nat_prefix'] }}"
    v6nat_addr: "{{ vault_env_conn_admin['ldev']['v6nat_addr'] }}"
    v6nat_net: "{{ vault_env_conn_admin['ldev']['v6nat_net'] }}"
    v6nat_prefix: "{{ vault_env_conn_admin['ldev']['v6nat_prefix'] }}"
    v6natnet_ula: "{{ vault_env_conn_admin['ldev']['v6natnet_ula'] }}"
    vbridge: "{{ vault_env_conn_admin['ldev']['vbridge'] }}"
env_default_userdata:
  ldev:
    apt:
      preserve_sources_list: true
      http_proxy: "{{ vault_env_default_userdata['ldev']['apt']['http_proxy'] }}"
    groups:
    - adm
    - sudo
    - sudonp
    - sys
    ntp_servers:
    - "{{ env_conn_admin['ldev']['v4nat_addr'] }}"
    - "{{ env_conn_admin['ldev']['v6nat_addr'] }}"
    packages:
    - molly-guard
    - powermgmt-base
    - python3-gi
    - ufw
    - unattended-upgrades
    runcmd_before:
    - [set, -xe]
    - [systemctl, reload, apparmor]
    runcmd_after:
    - [bash, /run/ci-files/conf-ufw]
    # - [systemctl, daemon-reload]
    - [systemctl, restart, networking]
    - [rm, -rf, /run/ci-files]
    users:
    - name: "{{ env_conn_admin['ldev']['admin_user'] }}"
      gecos: "{{ env_conn_admin['ldev']['admin_gecos'] }}"
      groups:
      - adm
      - sudo
      - sudonp
      homedir: "{{ env_conn_admin['ldev']['admin_base_homedir'] }}/{{ env_conn_admin['ldev']['admin_user'] }}"
      lock_passwd: true
      shell: /bin/bash
      ssh_authorized_keys:
      - no-agent-forwarding,no-port-forwarding {{ env_conn_admin['ldev']['admin_ssh_key_userdata'] }}
    write_files:
    - content: "{{ '%sudonp ALL=(ALL) NOPASSWD: ALL' | b64encode }}"
      encoding: b64
      path: /etc/sudoers.d/sudonp
      permissions: "0400"
    - content: "{{ lookup('file', '50unattended-upgrades') | b64encode }}"
      encoding: b64
      path: /etc/apt/apt.conf.d/50unattended-upgrades
    - content: "{{ lookup('template', 'conf-ufw.j2') | b64encode }}"
      encoding: b64
      path: /run/ci-files/conf-ufw
      permissions: "0755"
    - content: "{{ lookup('template', 'jail.local.j2') | b64encode }}"
      encoding: b64
      path: /etc/fail2ban/jail.local
    - content: "{{ lookup('template', 'interfaces-ipv6.j2') | b64encode }}"
      encoding: b64
      path: /etc/network/interfaces.d/60-ens2-ipv6
    - content: "{{ lookup('template', 'local-home.site.local.j2') | b64encode }}"
      encoding: b64
      path: /etc/apparmor.d/tunables/home.d/local-home.site.local
    - content: "{{ lookup('template', 'sshd_custom.conf.j2') | b64encode }}"
      encoding: b64
      path: /etc/ssh/sshd_config.d/sshd_custom.conf
    - content: "{{ lookup('template', 'sshd_jail.local.j2') | b64encode }}"
      encoding: b64
      path: /etc/fail2ban/jail.d/ssh.local
env_depends_conn_admin:
  bare_metal_local:
    mail_local_destinations: "{{ default_mail_local_destinations }}"
    remote_ignore_ips: "{{ remote_admin_ip }}{% if remote_monitoring_ips is defined %} {{ remote_monitoring_ips }}{% endif %}"
  ldev:
    mail_local_destinations: "{{ default_mail_local_destinations }}"
    remote_ignore_ips: "{{ remote_admin_ip }}{% if remote_monitoring_ips is defined %} {{ remote_monitoring_ips }}{% endif %}"
env_guest_userdata:
  ldev:
    airlock:
      fqdn: "{{ vault_env_guest_userdata['ldev']['airlock']['fqdn'] }}"
      hostname: airlockldev
      packages:
      - fail2ban
      runcmd:
      - [systemctl, restart, fail2ban]
      users:
      - name: "{{ env_conn_admin['ldev']['bastion_user'] }}"
        homedir: "{{ admin_base_homedir }}/{{ env_conn_admin['ldev']['bastion_user'] }}"
        lock_passwd: true
        shell: /bin/bash
        ssh_authorized_keys:
        - "{{ env_conn_admin['ldev']['bastion_ssh_key'] }}"
external_rfc1618_domain: "{{ env_conn_admin[envname]['external_rfc1618_domain'] }}"
fallback_dns: "{{ env_conn_admin[envname]['fallback_dns'] }}"
internal_domain: "{{ env_conn_admin[envname]['internal_domain'] }}"
internal_fqdn: "{{ ansible_facts['hostname'] }}.{{ internal_domain }}"
internal_relay_port: "{{ env_conn_admin[envname]['internal_relay_port'] }}"
libvirt_client_ssh_key: "{{ env_conn_admin[envname]['libvirt_client_ssh_key'] }}"
libvirt_client_user: "{{ env_conn_admin[envname]['libvirt_client_user'] }}"
libvirt_guest_definitions: "{{ vault_libvirt_guest_definitions }}"
libvirt_os_base_image_name: debian-11-generic-amd64-20221205-1220.qcow2
libvirt_os_cloud_image_sha512sums_url: "https://cloud.debian.org/images/cloud/bullseye/20221205-1220/SHA512SUMS"
libvirt_os_cloud_image_url: "https://cloud.debian.org/images/cloud/bullseye/20221205-1220/debian-11-generic-amd64-20221205-1220.qcow2"
local_ipv6_cidr: "{{ env_conn_admin[envname]['local_ipv6_cidr'] }}"
local_ipv6_gateway: "{{ env_conn_admin[envname]['local_ipv6_gateway'] }}"
mail_local_destinations: "{{ env_depends_conn_admin[envname]['mail_local_destinations'] }}"
public_cert_cert_file: "{{ host_public_cert_cert_file }}"
public_cert_key_file: "{{ host_public_cert_key_file }}"
public_cert_key_private_key: "{{ host_public_cert_private_key }}"
remote_admin_ip: "{{ env_conn_admin[envname]['remote_admin_ip'] }}"
remote_monitoring_ips: "{{ env_conn_admin[envname]['remote_monitoring_ips'] }}"
second_interface: "{{ host_second_interface }}"
storage_extra_use_lvm2: "{{ host_storage_extra_use_lvm2 }}"
storage_filesystems: "{{ host_storage_filesystems }}"
storage_logical_volumes: "{{ host_storage_logical_volumes }}"
storage_mountpoints: "{{ host_storage_mountpoints }}"
storage_mounts: "{{ host_storage_mounts }}"
storage_volume_groups: "{{ host_storage_volume_groups }}"
submission_port: "{{ vault_submission_port }}"
submission_relay_host: "{{ vault_submission_relay_host }}"
submission_relay_port: "{{ vault_submission_relay_port }}"
v6natnet_ula: "{{ env_conn_admin[envname]['v6natnet_ula'] }}"
well_known_admin_aliases: "{{ vault_well_known_admin_aliases }}"
...
