---
admin_base_homedir: "{{ env_conn_admin[envname]['admin_base_homedir'] }}"
admin_gecos: "{{ env_conn_admin[envname]['admin_gecos'] }}"
admin_password: "{{ env_conn_admin[envname]['admin_password'] }}"
admin_ssh_key: "{{ env_conn_admin[envname]['admin_ssh_key'] }}"
admin_ssh_key_userdata: "{{ env_conn_admin[envname]['admin_ssh_key_initial'] }}"
admin_user: "{{ env_conn_admin[envname]['admin_user'] }}"
ansible_become_password: "{{ env_conn_admin[envname]['ansible_become_password'] }}"
ansible_ssh_common_args: "{% if 'external_ssh' not in group_names %}-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -p {{ bastion_port }} -W %h:%p -q {{ bastion_user }}@{{ bastion_host }}\"{% endif %}"
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_port: "{{ env_conn_admin[envname]['ansible_ssh_port'] }}"
ansible_ssh_user: "{{ env_conn_admin[envname]['ansible_ssh_user'] }}"
backupmx_port: "{{ vault_backupmx_port }}"
bastion_host: "{{ vault_bastion_host }}"
bastion_port: "{{ vault_bastion_port }}"
bastion_user: "{{ vault_bastion_user }}"
bastion_ssh_key: "{{ vault_bastion_ssh_key }}"
central_local_domain: "{{ env_conn_admin[envname]['central_local_domain'] }}"
central_local_email: "{{ env_conn_admin[envname]['central_local_email'] }}"
dovecot_health_check_port: "{{ vault_dovecot_health_check_port }}"
env_conn_admin: "{{ vault_env_conn_admin }}"
env_default_userdata: "{{ vault_env_default_userdata }}"
env_depends_conn_admin: "{{ vault_env_depends_conn_admin }}"
env_guest_userdata: "{{ vault_env_guest_userdata }}"
external_rfc1618_domain: "{{ env_conn_admin[envname]['external_rfc1618_domain'] }}"
fallback_dns: "{{ env_conn_admin[envname]['fallback_dns'] }}"
imap_port: "{{ vault_imap_port }}"
internal_domain: "{{ env_conn_admin[envname]['internal_domain'] }}"
internal_fqdn: "{{ ansible_facts['hostname'] }}.{{ internal_domain }}"
internal_relay_port: "{{ env_conn_admin[envname]['internal_relay_port'] }}"
libvirt_client_ssh_key: "{{ env_conn_admin[envname]['libvirt_client_ssh_key'] }}"
libvirt_client_user: "{{ env_conn_admin[envname]['libvirt_client_user'] }}"
libvirt_env_definitions: "{{ vault_libvirt_env_definitions }}"
libvirt_guest_definitions: "{{ vault_libvirt_guest_definitions }}"
libvirtd_pool_list: "{{ host_libvirtd_pool_list }}"
local_admin_user: "{{ admin_user }}"
local_ipv6_cidr: "{{ env_conn_admin[envname]['local_ipv6_cidr'] }}"
local_ipv6_gateway: "{{ env_conn_admin[envname]['local_ipv6_gateway'] }}"
mail_local_destinations: "{{ env_depends_conn_admin[envname]['mail_local_destinations'] }}"
mx_mail_users: "{{ vault_mx_mail_users }}"
private_ca_cert_certificate: "{{ vault_private_ca_cert_certificate }}"
private_ca_cert_file: "{{ vault_private_ca_cert_file }}"
proxied_imap_port: "{{ vault_proxied_imap_port }}"
proxied_submission_port: "{{ vault_proxied_submission_port }}"
public_cert_cert_file: "{{ host_public_cert_cert_file }}"
public_cert_key_file: "{{ host_public_cert_key_file }}"
public_cert_key_private_key: "{{ host_public_cert_private_key }}"
remote_admin_ip: "{{ env_conn_admin[envname]['remote_admin_ip'] }}"
remote_monitoring_ips: "{{ env_conn_admin[envname]['remote_monitoring_ips'] }}"
second_interface: "{{ host_second_interface }}"
storage_extra_use_lvm2: "{{ host_storage_extra_use_lvm2 }}"
storage_filesystems: "{{ host_storage_filesystems }}"
storage_logical_volumes: "{{ host_storage_logical_volumes }}"
storage_mountpoints: "{{ host_storage_mountpoints }}"
storage_mounts: "{{ host_storage_mounts }}"
storage_volume_groups: "{{ host_storage_volume_groups }}"
submission_port: "{{ vault_submission_port }}"
submission_relay_host: "{{ vault_submission_relay_host }}"
submission_relay_port: "{{ vault_submission_relay_port }}"
v6natnet_ula: "{{ vault_v6natnet_ula }}"
well_known_admin_aliases: "{{ vault_well_known_admin_aliases }}"
...
