---
ansible_become_password: "{{ vault_ansible_become_password }}"
ansible_ssh_common_args: "{% if 'external_ssh' not in group_names %}-o ProxyCommand=\"ssh -o StrictHostKeyChecking=no -p {{ vault_bastion_port }} -W %h:%p -q {{ vault_bastion_user }}@{{ vault_bastion_host }}\"{% endif %}" # yamllint disable-line
ansible_ssh_host_key_checking: false # Note: this should be true in production
ansible_ssh_port: "{{ vault_ansible_port }}"
ansible_ssh_user: "{{ vault_admin_user }}"
central_local_domain: "{{ vault_central_local_domain }}"
central_local_email: "{{ vault_central_local_email }}"
dovecot_health_check_port: "{{ vault_dovecot_health_check_port }}"
envname: "{{ vault_envname }}"
external_rfc1618_domain: "{{ vault_external_rfc1618_domain }}"
fallback_dns: "{{ vault_fallback_dns }}"
imap_port: "{{ vault_imap_port }}"
internal_domain: "{{ vault_envname }}"
internal_fqdn: "{{ ansible_facts['hostname'] }}.{{ internal_domain }}"
internal_relay_port: "{{ vault_internal_relay_port }}"
libvirt_domain_forwards: "{{ vault_libvirt_domain_forwards }}"
libvirt_domain_ssh_forwards: "{{ vault_libvirt_domain_ssh_forwards }}"
lmtp_port: "{{ vault_lmtp_port }}"
local_admin_user: "{{ vault_admin_user }}"
mail_local_host_destinations:
- localhost
- localhost.localdomain
- "{{ ansible_facts['hostname'] }}.localdomain"
- localhost.{{ ansible_facts['domain'] }}
- localhost.{{ internal_domain }}
- "{{ internal_fqdn }}"
- "{{ ansible_facts['fqdn'] }}"
mailbox_users: "{{ vault_mailbox_users }}"
mx_mail_users: "{{ vault_mx_mail_users }}"
private_ca_cert_certificate: "{{ vault_private_ca_cert_certificate }}"
private_ca_cert_file: "{{ vault_private_ca_cert_file }}"
private_cert_cert_content: "{{ vault_private_cert_cert_content }}"
private_cert_key_content: "{{ vault_private_cert_key_content }}"
private_cert_cert_file: "{{ vault_private_cert_cert_file }}"
private_cert_key_file: "{{ vault_private_cert_key_file }}"
proxied_imap_port: "{{ vault_proxied_imap_port }}"
proxied_submission_port: "{{ vault_proxied_submission_port }}"
public_cert_cert_file: "{{ vault_public_cert_cert_file }}"
public_cert_key_file: "{{ vault_public_cert_key_file }}"
remote_admin_ip: "{{ vault_remote_admin_ip }}"
remote_monitoring_ips: "{{ vault_remote_monitoring_ips }}"
submission_port: "{{ vault_submission_port }}"
submission_relay_host: "{{ vault_submission_relay_host }}"
submission_relay_port: "{{ vault_submission_relay_port }}"
well_known_admin_aliases:
- "{{ local_admin_user }}"
- root
- spampolice
- virusalert
# - admin # If local_admin_user is 'admin' this is a duplicate
- bin
- daemon
- named
- nobody
- uucp
- www
- ftp-bugs
- postfix
- manager
- dumper
- operator
- abuse
- decode
vbridge: "{{ vault_vbridge }}"
...
