---
- name: Make default fqdn or hostname to IP be the default external ipv4 address
  become: yes
  ansible.builtin.template:
    dest: /etc/hosts
    group: root
    mode: "0644"
    owner: root
    src: hosts.j2
- name: Preserve default fqdn or hostname to IP map across reboots
  become: yes
  ansible.builtin.template:
    dest: /etc/cloud/templates/hosts.debian.tmpl
    group: root
    mode: "0644"
    owner: root
    src: hosts.debian.tmpl.j2

...
