---
- name: Enable PROXY Protocol from HAProxy
  become: yes
  block:
  - name: Ensure apache2 present
    ansible.builtin.apt:
      name:
      - apache2
      - apache2-utils
      state: present
  - name: Add configuration for PROXY protocol
    ansible.builtin.copy:
      dest: /etc/apache2/conf-available/haproxy-proxy-protocol.conf
      group: root
      mode: "0644"
      owner: root
      src: haproxy-proxy-protocol.conf
  - name: Enable configuration for PROXY Protocol
    become: yes
    ansible.builtin.file:
      path: /etc/apache2/conf-enabled/haproxy-proxy-protocol.conf
      src: ../conf-available/haproxy-proxy-protocol.conf
      state: link
    notify: Restart Apache2
  - name: Enable remoteip module (for PROXY protocol)
    community.general.apache2_module:
      name: remoteip
      state: present
    notify: Restart Apache2
...
