---
- name: Ensure NUT client is installed
  become: yes
  ansible.builtin.apt:
    name:
    - nut-client
- name: Configure NUT startup mode
  become: yes
  ansible.builtin.copy:
    content: MODE=netclient
    dest: /etc/nut/nut.conf
    group: nut
    mode: "0640"
    owner: root
  notify: Restart NUT monitor
- name: Configure NUT monitor (upsmon)
  become: yes
  ansible.builtin.template:
    dest: /etc/nut/upsmon.conf
    group: nut
    mode: "0640"
    owner: root
    src: upsmon.j2
  notify: Restart NUT monitor
- name: Enable NUT monitor (upsmon)
  become: yes
  ansible.builtin.systemd:
    name: nut-monitor.service
    enabled: true
  notify: Restart NUT monitor
...
