---
dependencies:
- role: system_fail2ban
  vars:
    f2b_jails:
    - content: "{{ lookup('template', 'mx_jail.local.j2') }}"
      dest: mx
- role: packages_postfix
- role: packages_clamav_milter
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure postfix as external MX
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
