---
dependencies:
- role: system_fail2ban
  vars:
    f2b_jails:
    - content: "{{ lookup('template', 'mx_jail.local.j2') }}"
      dest: mx
- role: packages_postfix
- role: system_cert_ca_private
- role: system_policyd_spf_python
- role: system_clamav_milter
- role: system_spamass_milter
- role: system_ufw
  vars:
    ufw_role_rules:
    - port: "{{ backupmx_port }}"
    - port: "{{ smtp_port }}"
    - port: "{{ submission_relay_port }}"
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure postfix as external MX
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
