---
- name: Upgrade packages if needed and clean up packages
  become: yes
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
    purge: true
    upgrade: yes
- name: Ensure our packages for expected apt behaviour are installed
  become: yes
  ansible.builtin.apt:
    name:
    - needrestart
    state: present
...
