---
dependencies:
- role: packages_libvirtd
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure libvirt virtualisation
  license: MIT
  min_ansible_version: 2.14.1
  platforms:
  - name: Debian
    versions:
    - all
...
