---
dependencies:
- role: system_fail2ban
  vars:
    f2b_jails:
    - content: "{{ lookup('template', 'ssh_jail.local.j2') }}"
      dest: ssh
# Because ansible-lint complains otherwise
galaxy_info:
  author: Daniel F. Dickinson <dfdpublic@wildtechgarden.ca>
  description: Configure SSH fail2ban jail
  license: MIT
  min_ansible_version: "6.0"
  platforms:
  - name: Debian
    versions:
    - all
...
