---
ansible_ssh_port: "{{ vault_ansible_port }}"
email_relayhost: "[hostvars[{{ vault_email_relay_fqdn }}]['ansible_facts']['ens3']['ipv4']['address']]:{{ internal_relay_port }}" # yamllint disable-line
pool_list: "{{ vault_pool_list }}"
second_interface: "{{ vault_second_interface }}"
storage_filesystems: "{{ vault_storage_filesystems }}"
storage_logical_volumes: "{{ vault_storage_logical_volumes }}"
storage_mountpoints: "{{ vault_storage_mountpoints }}"
storage_mounts: "{{ vault_storage_mounts }}"
storage_volume_groups: "{{ vault_storage_volume_groups }}"
...
