---
host_email_interfaces: "{{ vault_email_interfaces }}"
host_email_relayhost: "{{ vault_email_relayhost }}"
host_second_interface: "{{ vault_second_interface }}"
host_storage_extra_use_lvm2: "{{ vault_storage_extra_use_lvm2 }}"
host_storage_filesystems: "{{ vault_storage_filesystems }}"
host_storage_logical_volumes: "{{ vault_storage_logical_volumes }}"
host_storage_mountpoints: "{{ vault_storage_mountpoints }}"
host_storage_mounts: "{{ vault_storage_mounts }}"
host_storage_volume_groups: "{{ vault_storage_volume_groups }}"
host_libvirtd_pool_list: "{{ vault_libvirtd_pool_list }}"
host_local_ipv6_cidr: "{{ vault_local_ipv6_cidr }}"
host_local_ipv6_gateway: "{{ vault_local_ipv6_gateway }}"
...
