---
- name: Add and configure bastion user
  become: yes
  block:
  - name: Add bastion user
    ansible.builtin.user:
      name: "{{ env_conn_admin[envname]['bastion_user'] }}"
      home: "{{ admin_base_homedir }}/{{ env_conn_admin[envname]['bastion_user'] }}"
      password_lock: true
      shell: /bin/bash
      state: present
    notify: Restart SSH server
  - name: Lockdown bastion user home dir
    ansible.builtin.file:
      path: "{{ admin_base_homedir }}/{{ env_conn_admin[envname]['bastion_user'] }}"
      group: "{{ env_conn_admin[envname]['bastion_user'] }}"
      mode: "0700"
      owner: "{{ env_conn_admin[envname]['bastion_user'] }}"
      state: directory
  - name: Lockdown bastion user ssh dir
    ansible.builtin.file:
      path: "{{ admin_base_homedir }}/{{ env_conn_admin[envname]['bastion_user'] }}/.ssh"
      group: "{{ env_conn_admin[envname]['bastion_user'] }}"
      mode: "0700"
      owner: "{{ env_conn_admin[envname]['bastion_user'] }}"
      state: directory
  - name: Add bastion user incoming public key
    ansible.builtin.template:
      dest: "{{ admin_base_homedir }}/{{ env_conn_admin[envname]['bastion_user'] }}/.ssh/authorized_keys"
      group: "{{ env_conn_admin[envname]['bastion_user'] }}"
      mode: "0600"
      owner: "{{ env_conn_admin[envname]['bastion_user'] }}"
      src: authorized_keys.j2
...
