---
- name: Add and configure bastion user
  become: yes
  block:
  - name: Add bastion user
    ansible.builtin.user:
      name: "{{ vault_bastion_user }}"
      home: /local-home/{{ vault_bastion_user }}
      password_lock: true
      shell: /bin/bash
      state: present
    notify: Restart SSH server
  - name: Lockdown bastion user home dir
    ansible.builtin.file:
      path: /local-home/{{ vault_bastion_user }}
      group: "{{ vault_bastion_user }}"
      mode: "0700"
      owner: "{{ vault_bastion_user }}"
      state: directory
  - name: Lockdown bastion user ssh dir
    ansible.builtin.file:
      path: /local-home/{{ vault_bastion_user }}/.ssh
      group: "{{ vault_bastion_user }}"
      mode: "0700"
      owner: "{{ vault_bastion_user }}"
      state: directory
  - name: Add bastion user incoming public key
    ansible.builtin.template:
      dest: /local-home/{{ vault_bastion_user }}/.ssh/authorized_keys
      content: "{{ vault_bastion_ssh_key }}"
      group: "{{ vault_bastion_user }}"
      mode: "0600"
      owner: "{{ vault_bastion_user }}"
...
