---
- name: Refresh list of volumes in base-images pool
  become: yes
  ansible.builtin.command: virsh pool-refresh {{ libvirt_pool_base_images | quote }}
- name: Refresh list of volumes in fast pool
  become: yes
  ansible.builtin.command: virsh pool-refresh fast
- name: Refresh list of volumes in slow pool
  become: yes
  ansible.builtin.command: virsh pool-refresh slow
- name: Refresh list of volumes in pool containing cloud-init images
  become: yes
  ansible.builtin.command: virsh pool-refresh {{ libvirt_pool_cloud_init | quote }}
- name: Create nocloud image
  ansible.builtin.command:
    argv:
    - mcopy
    - -oi
    - nocloud.img
    - user-data
    - meta-data
    - "::"
    chdir: "{{ nocloud_img_size.path | dirname }}"
...
