---
- name: Add fail2ban SSH config
  become: yes
  ansible.builtin.template:
    dest: /etc/fail2ban/jail.d/ssh.local
    group: root
    mode: "0644"
    owner: root
    src: ssh_jail.local.j2
  notify: Reload fail2ban
...
