---
apache2_global_https_port: 443
conf_default_remove:
- localized-error-pages
- serve-cgi-bin
conf_default_add:
- global-log
- ha-proxy-protocol
conf_conf_list:
- global-log
- ha-proxy-protocol
...
