---
- name: Restart libvirtd
  become: yes
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  notify: Restart changed libvirt guests
  # yamllint disable rule:line-length
- name: Identify changed guests
  ansible.builtin.command: echo "{{ item.item.name | quote }}"
  loop: "{{ hooks_qemu_result.results }}"
  when: item.changed
  register: changed_guests
  changed_when: stdout is defined and stdout != ""
  listen: Restart changed libvirt guests
- name: Stop changed libvirt guests
  become: yes
  ansible.builtin.command: virsh suspend {{ item | quote }}
  loop: "{{ changed_guests.results | map(attribute='stdout') | unique }}"
  when:
  - item is defined
  - item != """
  listen: Restart changed libvirt guests
- name: Start changed libvirt guests
  become: yes
  ansible.builtin.command: virsh resume {{ item | quote }}
  loop: "{{ changed_guests.results | map(attribute='stdout') | unique }}"
  when:
  - item is defined
  - item != """
  listen: Restart changed libvirt guests
- name: Flush handlers in handlers
  ansible.builtin.meta: flush_handlers
...
