---
- name: List all volumes in libvirtd pool for desired volume
  become: yes
  ansible.builtin.shell:
    cmd: virsh vol-list --pool {{ item.pool | quote }} | tail -n+3 | awk '{ print $1 }'
  register: libvirt_data_vol_list
  changed_when: false
- name: Create data volume {{ item.name }} for instance {{ instance_item.key }} in {{ guest_envname }}
  become: yes
  ansible.builtin.command: virsh vol-create-as {{ item.pool | quote }} {{ item.name | quote }} {{ item.vol_size | quote }} --format qcow2 --prealloc-metadata
  register: datavol_create_out
  changed_when: datavol_create_out.rc == 0
  when: item.name not in libvirt_data_vol_list.stdout_lines
...
