---
- name: Add and configure libvirt client user
  become: yes
  block:
  - name: Add libvirt client user
    ansible.builtin.user:
      name: "{{ libvirt_client_user }}"
      groups:
      - libvirt
      home: "{{ admin_base_homedir }}/{{ libvirt_client_user }}"
      password_lock: true
      shell: /bin/bash
      state: present
    notify: Restart SSH server
  - name: Lockdown libvirt client user home dir
    ansible.builtin.file:
      path: "{{ admin_base_homedir }}/{{ libvirt_client_user }}"
      group: "{{ libvirt_client_user }}"
      mode: "0700"
      owner: "{{ libvirt_client_user }}"
      state: directory
  - name: Lockdown libvirt client user ssh dir
    ansible.builtin.file:
      path: "{{ admin_base_homedir }}/{{ libvirt_client_user }}/.ssh"
      group: "{{ libvirt_client_user }}"
      mode: "0700"
      owner: "{{ libvirt_client_user }}"
      state: directory
  - name: Add libvirt client user incoming public key
    ansible.builtin.template:
      dest: "{{ admin_base_homedir }}/{{ libvirt_client_user }}/.ssh/authorized_keys"
      group: "{{ libvirt_client_user }}"
      mode: "0600"
      owner: "{{ libvirt_client_user }}"
      src: authorized_keys.j2
...
