---
- name: Ensure fail2ban installed
  become: yes
  ansible.builtin.apt:
    name:
    - fail2ban
    state: present
- name: Add fail2ban defaults
  become: yes
  ansible.builtin.template:
    dest: /etc/fail2ban/jail.local
    group: root
    mode: "0644"
    owner: root
    src: jail.local.j2
  notify: Reload fail2ban
...
