---
- name: Add directory for private certificates and keys
  become: yes
  ansible.builtin.file:
    group: root
    mode: "0755"
    owner: root
    path: /etc/ssl/privcert
    state: directory
- name: Add private server certificate as file
  become: yes
  when: host_private_cert_cert_file is defined
  ansible.builtin.template:
    dest: "{{ host_private_cert_cert_file }}"
    group: root
    mode: "0644"
    owner: root
    src: private_cert-cert.pem.j2
  notify:
  - Restart SSL-based server
- name: Add private key for private server cert, as file
  become: yes
  when: host_private_cert_key_file is defined
  ansible.builtin.template:
    dest: "{{ host_private_cert_key_file }}"
    group: root
    mode: "0600"
    owner: root
    src: private_cert-key.pem.j2
  notify:
  - Restart SSL-based server
- name: Add full private server cert as file
  become: yes
  when: host_private_cert_full_file is defined
  ansible.builtin.template:
    dest: "{{ host_private_cert_full_file }}"
    group: root
    mode: "0600"
    owner: root
    src: private_cert-full.pem.j2
  notify:
  - Restart SSL-based server
...
