---
- name: Disable cloud-init network config
  become: yes
  ansible.builtin.copy:
    content: "network: {config: disabled}"
    dest: /etc/cloud/cloud.cfg.d/99_disable-network-config.cfg
    group: root
    mode: "0644"
    owner: root
- name: Prevent using cloud-init generated interfaces snippets
  become: yes
  ansible.builtin.copy:
    dest: /etc/network/interfaces
    group: root
    mode: "0644"
    owner: root
    src: interfaces
- name: Install bridge utilities
  become: yes
  ansible.builtin.apt:
    name:
    - bridge-utils
    state: present
- name: Update cloud-init generated interface file for new config
  become: yes
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/50-cloud-init
    group: root
    mode: "0644"
    owner: root
    src: 50-cloud-init.j2
  notify: Restart networking to start br1
- name: Configure br1 on second interface
  become: yes
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/70-br1
    group: root
    mode: "0644"
    owner: root
    src: br1.j2
  notify: Restart networking to start br1
...
