---
- name: Create XML for ipv4 and ipv6 NAT based network
  become: yes
  ansible.builtin.template:
    dest: /root/v4v6natnet-{{ envname }}.xml
    group: root
    mode: "0600"
    owner: root
    src: v4v6natnet.xml.j2
  register: net_xml_out
- name: List networks on libvirtd host
  become: yes
  ansible.builtin.command:
    cmd: virsh net-list --all --name
  register: net_list_out
  changed_when: false
  failed_when: envname in net_list_out.stdout_lines and net_xml_out.changed
- name: Define ipv4 and ipv6 NAT based network
  become: yes
  ansible.builtin.command: virsh net-define /root/v4v6natnet-{{ envname }}.xml
  when: envname not in net_list_out.stdout_lines
  register: net_define_out
  changed_when: net_define_out.rc == 0
  notify: Start v4v6natnet and set autostarted
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
...
