---
- name: Restart postfix
  listen: Restart SSL-based server
  become: yes
  ansible.builtin.service:
    name: postfix
    state: restarted
- name: Apply email aliases
  become: yes
  ansible.builtin.command: newaliases
...
