---
- name: Make sure firewall package present
  become: yes
  ansible.builtin.apt:
    name:
    - ufw
    state: present
- name: Make Libvirt qemu hook parts directory
  become: yes
  ansible.builtin.file:
    path: /etc/libvirt-forward-hooks.d
    group: root
    mode: "0755"
    owner: root
    state: directory
- name: Add Libvirt main qemu hook
  become: yes
  ansible.builtin.copy:
    dest: /etc/libvirt/hooks/qemu
    group: root
    mode: "0755"
    owner: root
    src: hooks-qemu-main
  notify: Restart libvirtd
  # yamllint disable rule:line-length
- name: Add Libvirt qemu hook parts
  become: yes
  ansible.builtin.template:
    dest: /etc/libvirt-forward-hooks.d/{{ item.name }}_{{ item.host_port }}to{{ item.guest_port }}.hook
    group: root
    mode: "0755"
    owner: root
    src: hooks-qemu.j2
  loop: "{{ libvirt_domain_forwards_map }}"
  vars:
    item_guest_ip: "{{ item.guest_ip | default( hostvars[item.name  + '.' + internal_domain]['ansible_facts']['default_ipv4']['address'] | default('')) }}"
    item_guest_ip6: "{{ item.guest_ip6 | default( hostvars[item.name  + '.' + internal_domain]['ansible_facts']['default_ipv6']['address'] | default('')) }}"
  register: hooks_qemu_result
  notify: Restart libvirtd
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
...
