---
host_ansible_ssh_port: "{{ vault_host_ansible_ssh_port }}"
host_libvirt_pool_base_images: "{{ vault_host_libvirt_pool_base_images }}"
host_libvirt_pool_base_images_path: "{{ vault_host_libvirt_pool_base_images_path }}"
host_libvirt_pool_cloud_init: "{{ vault_host_libvirt_pool_cloud_init }}"
host_libvirt_pool_cloud_init_path: "{{ vault_host_libvirt_pool_cloud_init_path }}"
host_libvirtd_pool_list: "{{ vault_host_libvirtd_pool_list }}"
host_local_ipv6_addr: "{{ vault_host_local_ipv6_addr }}"
host_local_ipv6_gateway: "{{ vault_host_local_ipv6_gateway }}"
host_local_ipv6_prefix: "{{ vault_host_local_ipv6_prefix }}"
host_primary_interface: "{{ vault_host_primary_interface }}"
host_second_interface: "{{ vault_host_second_interface }}"
host_storage_extra_use_lvm2: "{{ vault_host_storage_extra_use_lvm2 }}"
host_storage_filesystems: "{{ vault_host_storage_filesystems }}"
host_storage_logical_volumes: "{{ vault_host_storage_logical_volumes }}"
host_storage_mountpoints: "{{ vault_host_storage_mountpoints }}"
host_storage_mounts: "{{ vault_host_storage_mounts }}"
host_storage_volume_groups: "{{ vault_host_storage_volume_groups }}"
nut_netclient_monitors:
- system: "{{ vault_host_ups_name }}@{{ vault_host_upsd_host }}"
  password: "{{ vault_host_upsd_password }}"
  powervalue: 1
  username: "{{ vault_host_upsd_user }}"
  type: "{{ vault_host_upsmon_type }}"
host_vbridge: "{{ vault_host_vbridge }}"
...
