---
- name: Ensure Postfix DH Param file is present (for public SSL)
  become: yes
  ansible.builtin.template:
    dest: "{{ smtpd_dh_param_file }}"
    group: postfix
    mode: "0640"
    owner: root
    src: dhparam.j2
  notify: Restart postfix
...
